### PR TITLE
feat: updates for 1.0.0

### PR DESCRIPTION
**Pull request by dschier-wtd**
Added the base and home server playbooks and some
minor tuning here and there.

### CODE REVIEW

**Comment by daniel-schier** [comment]
@xXluki98Xx It would be awesome, if you can have a look. The roles used in the playbooks should work on a minimal/core F36 machine/server. :)

I will also add another commit this week to push the collection to ansible galaxy.

**Comment by xXluki98Xx** [comment]
i get an error at the sshd role:
"The conditional check 'sshd_config_Banner != 'none'' failed. The error was: error while evaluating conditional (sshd_config_Banner != 'none'): 'sshd_config_Banner' is undefined

**Comment by daniel-schier** [comment]
Fixed the finding and also working on some more tests to mitigate such issues. The cirrus.yml is currently intended to publish the collection to https://galaxy.ansible.com/whiletruedoio. But since this is happening only on tags, I am also publishing the collection as a downloadable artifact beforehand.

**Comment by xXluki98Xx** [comment]
Now two steps further:

TASK [whiletruedoio.general.sshd : Manage sshd Configuration Files] **************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: {% endif %}
failed: [fedora-36.server.localvm] (item=authentication) => {"ansible_loop_var": "item", "changed": false, "item": "authentication", "msg": "AnsibleError: template error while templating string: expected token 'end of statement block', got 'defined'. String: {{ ansible_managed | comment }}\n\n## Auth\n\n{% if sshd_config_LoginGraceTime is defined %}\nLoginGraceTime {{ sshd_config_LoginGraceTime }}\n{% endif %}\n{% if sshd_config_PermitRootLogin is defined %}\nPermitRootLogin {{ sshd_config_PermitRootLogin }}\n{% endif %}\n\n{% if sshd_config_StrictModes is defined %}\nStrictModes {{ sshd_config_StrictModes }}\n{% endif %}\n{% if sshd_config_MaxAuthTries is defined %}\nMaxAuthTries {{ sshd_config_MaxAuthTries }}\n{% endif %}\n{% if  is defined %}\nMaxStartups {{ sshd_config_MaxStartups }}\n{% endif %}\n\n{% if sshd_config_PubkeyAuthentication is defined %}\nPubkeyAuthentication {{ sshd_config_PubkeyAuthentication }}\n{% endif %}\n{% if sshd_config_PasswordAuthentication is defined %}\nPasswordAuthentication {{ sshd_config_PasswordAuthentication }}\n{% endif %}\n{% if sshd_config_PermitEmptyPasswords is defined %}\nPermitEmptyPasswords {{ sshd_config_PermitEmptyPasswords }}\n{% endif %}\n"}
ok: [fedora-36.server.localvm] => (item=connection)
ok: [fedora-36.server.localvm] => (item=information)
ok: [fedora-36.server.localvm] => (item=logging)
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: {% endif %}
failed: [fedora-36.server.localvm] (item=session) => {"ansible_loop_var": "item", "changed": false, "item": "session", "msg": "AnsibleError: template error while templating string: expected token 'end of statement block', got 'defined'. String: {{ ansible_managed | comment }}\n\n## Session\n\n{%if  is defined %}\nClientAliveInterval {{ sshd_config_ClientAliveInterval }}\n{% endif %}\n{%if  is defined %}\nClientAliveCountMax {{ sshd_config_ClientAliveCountMax }}\n{% endif %}\n\n{%if  is defined %}\nMaxSessions {{sshd_config_MaxSessions }}\n{% endif %}\n{%if  is defined %}\nCompression {{ sshd_config_Compression }}\n{% endif %}\n{%if  is defined %}\nUsePrivilegeSeparation {{ sshd_config_UsePrivilegeSeparation }}\n{% endif %}\n{%if  is defined %}\nTCPKeepAlive {{ sshd_config_TCPKeepAlive }}\n{% endif %}\n\n{%if  is defined %}\nAllowAgentForwarding {{ sshd_config_AllowAgentForwarding }}\n{% endif %}\n{%if  is defined %}\nX11Forwarding {{ sshd_config_X11Forwarding }}\n{% endif %}\n"}

**Comment by daniel-schier** [comment]
I see. Have to have another look on the sshd role:)

**Comment by daniel-schier** [comment]
One more update x)

**Review by xXluki98Xx — COMMENTED** [review]
tested on local VM and Cloud, plain config works

**Pull request merged**
